/*
Multiples of 3 and 5
Problem 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

answer = 233168
*/

function problemOne() {
  let sum = 0;
  for (var i = 0; i < 1000; i++) {
    if (i%3 === 0 || i%5 === 0) {
      sum+=i;
    }
  }
  return sum;
}




/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

answer = 4613732
*/

function problemTwo() {
  let array = [1, 2];
  let sum = 0;
  while (array[array.length - 1] < 4000000) {
    array.push(array[array.length - 1] + array[array.length - 2]);
  }
  for (var i = 0; i < array.length; i++) {
    if (array[i]%2 === 0) {
      sum = sum + array[i];
    }
  }
  return sum;
}




/*
Largest prime factor
Problem 3
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

answer =
*/


function primeNumbers(num) {
  let primes = [];
  return primes;
}

function primeFactors(num) {

  let sum = 0;
  return sum;
}
// console.log(primeFactors());





/*
Largest palindrome product
Problem 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

answer = 906609
*/

function problemFour() {
  let dromes = [];
  for (var i = 999; i > 99; i--) {
    for (var k = 999; k > 99; k--) {
      let num = i * k;
      if (num.toString().split("").join("") === num.toString().split("").reverse().join("")){
        dromes.push(num);
      }
    }
  }
  return Math.max.apply(null, dromes);
}

/*
Smallest multiple
Problem 5
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

answer = 232792560
*/

function problemFive() {
  for (var i = 2520; i > i - 1; i++) {
    let counter = 0;
    for (var k = 1; k < 21; k++) {
      if (i%k === 0) {
        counter++;
        if (counter === 20) {
          return i;
        }
      }
    }
  }
}

/*
Sum square difference
Problem 6
The sum of the squares of the first ten natural numbers is,

12 + 22 + ... + 102 = 385
The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

answer = 25164150
*/

function problemSix() {
  let sum1 = 0;
  let sum2 = 0;
  for (var i = 1; i < 101; i++) {
    sum1 += Math.pow(i, 2);
  }
  for (var i = 1; i < 101; i++) {
    sum2 += i;
  }
  return Math.pow(sum2, 2) - sum1;
}




/*
10001st prime
Problem 7
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10001st prime number?

answer = 104743
*/

function problemSeven() {
  let primes = [2];
  for (var i = 3; i < i + 1; i++) {
    let test = [];
    for (var k = 2; k < i; k++) {
      if ((i%k != 0) && ((i/k)%1 != 0)) {
        test.push(i);
        if (test.length === i - 2) {
          primes.push(i);
          if (primes.length === 10001) {
            return primes[primes.length - 1]
          }
        }
      }
    }
  }
}
